buildVariable: true
familyName: Noto Sans Georgian
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
- from: Noto Sans
  ranges:
    - start: 0x2116
      end: 0x2116
sources:
- NotoSansGeorgian.glyphspackage
