buildVariable: true
category:
- SERIF
familyName: Noto Serif Georgian
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
- from: Noto Serif
  ranges:
  - end: 8470
    start: 8470
recipeProvider: noto
sources:
- NotoSerifGeorgian.glyphspackage
