buildVariable: true
familyName: Noto Sans Georgian
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
- from: Noto Sans
  ranges:
  - end: 8470
    start: 8470
recipeProvider: noto
sources:
- NotoSansGeorgian.glyphspackage
